from .base import BaseECCBackend
from .coincurve import CoinCurveECCBackend, is_coincurve_available
from .native import NativeECCBackend
from typing import Optional

def get_default_backend_class() -> str: ...
def get_backend_class(import_path: Optional[str]=...) -> type: ...
def get_backend(import_path: Optional[str]=...) -> BaseECCBackend: ...
