__title__ = 'py-evm'
__description__ = 'Python implementation of the Ethereum Virtual Machine'
__url__ = 'https://github.com/pipermerriam/py-evm'
__version__ = "0.2.0-alpha.1"
__author__ = 'Piper Merriam'
__author_email__ = 'pipermerriam@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2017 %s' % __author__
__build__ = '[TODO] STUB'
