# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/ethresearch/sharding-p2p-poc/pb/event/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.ethresearch.sharding_p2p_poc.pb.message import message_pb2 as github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/ethresearch/sharding-p2p-poc/pb/event/event.proto',
  package='proto.event',
  syntax='proto3',
  serialized_pb=_b('\n<github.com/ethresearch/sharding-p2p-poc/pb/event/event.proto\x12\x0bproto.event\x1a@github.com/ethresearch/sharding-p2p-poc/pb/message/message.proto\"\t\n\x07MetaMsg\"l\n\x16NotifyCollationRequest\x12%\n\x07metaMsg\x18\x01 \x01(\x0b\x32\x14.proto.event.MetaMsg\x12+\n\tcollation\x18\x02 \x01(\x0b\x32\x18.proto.message.Collation\"S\n\x17NotifyCollationResponse\x12\'\n\x08response\x18\x01 \x01(\x0b\x32\x15.proto.event.Response\x12\x0f\n\x07isValid\x18\x02 \x01(\x08\"k\n\x13GetCollationRequest\x12%\n\x07metaMsg\x18\x01 \x01(\x0b\x32\x14.proto.event.MetaMsg\x12\x0f\n\x07shardID\x18\x02 \x01(\x03\x12\x0e\n\x06period\x18\x03 \x01(\x03\x12\x0c\n\x04hash\x18\x04 \x01(\t\"l\n\x14GetCollationResponse\x12\'\n\x08response\x18\x01 \x01(\x0b\x32\x15.proto.event.Response\x12+\n\tcollation\x18\x03 \x01(\x0b\x32\x18.proto.message.Collation\"m\n\x08Response\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.proto.event.Response.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"N\n\x0eReceiveRequest\x12\x0e\n\x06peerID\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07msgType\x18\x03 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"H\n\x0fReceiveResponse\x12\'\n\x08response\x18\x01 \x01(\x0b\x32\x15.proto.event.Response\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\x86\x02\n\x05\x45vent\x12^\n\x0fNotifyCollation\x12#.proto.event.NotifyCollationRequest\x1a$.proto.event.NotifyCollationResponse\"\x00\x12U\n\x0cGetCollation\x12 .proto.event.GetCollationRequest\x1a!.proto.event.GetCollationResponse\"\x00\x12\x46\n\x07Receive\x12\x1b.proto.event.ReceiveRequest\x1a\x1c.proto.event.ReceiveResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2.DESCRIPTOR,])



_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='proto.event.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=643,
  serialized_end=677,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_METAMSG = _descriptor.Descriptor(
  name='MetaMsg',
  full_name='proto.event.MetaMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=152,
)


_NOTIFYCOLLATIONREQUEST = _descriptor.Descriptor(
  name='NotifyCollationRequest',
  full_name='proto.event.NotifyCollationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metaMsg', full_name='proto.event.NotifyCollationRequest.metaMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collation', full_name='proto.event.NotifyCollationRequest.collation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=262,
)


_NOTIFYCOLLATIONRESPONSE = _descriptor.Descriptor(
  name='NotifyCollationResponse',
  full_name='proto.event.NotifyCollationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.event.NotifyCollationResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isValid', full_name='proto.event.NotifyCollationResponse.isValid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=347,
)


_GETCOLLATIONREQUEST = _descriptor.Descriptor(
  name='GetCollationRequest',
  full_name='proto.event.GetCollationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metaMsg', full_name='proto.event.GetCollationRequest.metaMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shardID', full_name='proto.event.GetCollationRequest.shardID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='proto.event.GetCollationRequest.period', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='proto.event.GetCollationRequest.hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=456,
)


_GETCOLLATIONRESPONSE = _descriptor.Descriptor(
  name='GetCollationResponse',
  full_name='proto.event.GetCollationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.event.GetCollationResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collation', full_name='proto.event.GetCollationResponse.collation', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=566,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='proto.event.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.event.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.event.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=568,
  serialized_end=677,
)


_RECEIVEREQUEST = _descriptor.Descriptor(
  name='ReceiveRequest',
  full_name='proto.event.ReceiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peerID', full_name='proto.event.ReceiveRequest.peerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='proto.event.ReceiveRequest.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='proto.event.ReceiveRequest.msgType', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.event.ReceiveRequest.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=757,
)


_RECEIVERESPONSE = _descriptor.Descriptor(
  name='ReceiveResponse',
  full_name='proto.event.ReceiveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.event.ReceiveResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.event.ReceiveResponse.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=759,
  serialized_end=831,
)

_NOTIFYCOLLATIONREQUEST.fields_by_name['metaMsg'].message_type = _METAMSG
_NOTIFYCOLLATIONREQUEST.fields_by_name['collation'].message_type = github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2._COLLATION
_NOTIFYCOLLATIONRESPONSE.fields_by_name['response'].message_type = _RESPONSE
_GETCOLLATIONREQUEST.fields_by_name['metaMsg'].message_type = _METAMSG
_GETCOLLATIONRESPONSE.fields_by_name['response'].message_type = _RESPONSE
_GETCOLLATIONRESPONSE.fields_by_name['collation'].message_type = github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2._COLLATION
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE_STATUS.containing_type = _RESPONSE
_RECEIVERESPONSE.fields_by_name['response'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['MetaMsg'] = _METAMSG
DESCRIPTOR.message_types_by_name['NotifyCollationRequest'] = _NOTIFYCOLLATIONREQUEST
DESCRIPTOR.message_types_by_name['NotifyCollationResponse'] = _NOTIFYCOLLATIONRESPONSE
DESCRIPTOR.message_types_by_name['GetCollationRequest'] = _GETCOLLATIONREQUEST
DESCRIPTOR.message_types_by_name['GetCollationResponse'] = _GETCOLLATIONRESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ReceiveRequest'] = _RECEIVEREQUEST
DESCRIPTOR.message_types_by_name['ReceiveResponse'] = _RECEIVERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaMsg = _reflection.GeneratedProtocolMessageType('MetaMsg', (_message.Message,), dict(
  DESCRIPTOR = _METAMSG,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.MetaMsg)
  ))
_sym_db.RegisterMessage(MetaMsg)

NotifyCollationRequest = _reflection.GeneratedProtocolMessageType('NotifyCollationRequest', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYCOLLATIONREQUEST,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.NotifyCollationRequest)
  ))
_sym_db.RegisterMessage(NotifyCollationRequest)

NotifyCollationResponse = _reflection.GeneratedProtocolMessageType('NotifyCollationResponse', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYCOLLATIONRESPONSE,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.NotifyCollationResponse)
  ))
_sym_db.RegisterMessage(NotifyCollationResponse)

GetCollationRequest = _reflection.GeneratedProtocolMessageType('GetCollationRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOLLATIONREQUEST,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.GetCollationRequest)
  ))
_sym_db.RegisterMessage(GetCollationRequest)

GetCollationResponse = _reflection.GeneratedProtocolMessageType('GetCollationResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCOLLATIONRESPONSE,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.GetCollationResponse)
  ))
_sym_db.RegisterMessage(GetCollationResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.Response)
  ))
_sym_db.RegisterMessage(Response)

ReceiveRequest = _reflection.GeneratedProtocolMessageType('ReceiveRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEREQUEST,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.ReceiveRequest)
  ))
_sym_db.RegisterMessage(ReceiveRequest)

ReceiveResponse = _reflection.GeneratedProtocolMessageType('ReceiveResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVERESPONSE,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.ReceiveResponse)
  ))
_sym_db.RegisterMessage(ReceiveResponse)



_EVENT = _descriptor.ServiceDescriptor(
  name='Event',
  full_name='proto.event.Event',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=834,
  serialized_end=1096,
  methods=[
  _descriptor.MethodDescriptor(
    name='NotifyCollation',
    full_name='proto.event.Event.NotifyCollation',
    index=0,
    containing_service=None,
    input_type=_NOTIFYCOLLATIONREQUEST,
    output_type=_NOTIFYCOLLATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCollation',
    full_name='proto.event.Event.GetCollation',
    index=1,
    containing_service=None,
    input_type=_GETCOLLATIONREQUEST,
    output_type=_GETCOLLATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Receive',
    full_name='proto.event.Event.Receive',
    index=2,
    containing_service=None,
    input_type=_RECEIVEREQUEST,
    output_type=_RECEIVERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENT)

DESCRIPTOR.services_by_name['Event'] = _EVENT

# @@protoc_insertion_point(module_scope)
